Thinking Process:

1.  **Analyze the Request:**
    *   **Role:** K12 Math Algorithm Engineer / MathProject LiveShow Structure Homomorphic Output Engine (Qwen-8B-VL specialized).
    *   **Task:** Implement `def generate(level=1, **kwargs)` to generate radical simplification and arithmetic problems.
    *   **Constraints:**
        *   NO thinking process output.
        *   NO non-code content.
        *   Direct Python code only.
        *   Strict import rules (`random`, `math`, `fractions.Fraction`). No custom imports for RadicalOps/FractionOps (use injected ones).
        *   Core logic must use `(coeff, radicand)` tuples/lists internally.
        *   NO parsing LaTeX strings to get values.
        *   Use specific API functions: `RadicalOps.simplify_term`, `RadicalOps.format_term_unsimplified`, `RadicalOps.format_expression`, `FractionOps.create` (or just `Fraction`).
        *   **Homomorphic Constraint:** The prompt provides a "Dynamic Target Problem Type Reference": `$(-\frac{2}{3}\sqrt{5}) \\times 4\sqrt{7}$`. I must mirror this structure strictly. No randomizing the operation type if the target is provided, but since `generate` implies generating *new* problems based on level/kwargs while respecting the "Homomorphic" instruction which says "Mirror Target Problem Type Structure", I need to balance between generic generation and strict mirroring of the example given in section D/E.
        *   **Crucial Instruction:** Section E states: "If 'Dynamic Target Problem Type Reference' provides a complete calculable expression (including specific numbers), prohibit re-randomizing...". However, `generate` is usually expected to generate random instances unless told otherwise. But the prompt says "Mirror target problem type structure" and gives an example `$(-\frac{2}{3}\sqrt{5}) \\times 4\sqrt{7}$`.
        *   **Wait, looking closer at Section E:** "If 'Dynamic Target Problem Type Reference' has provided a complete calculable expression... prohibit re-randomizing". This suggests I should follow the structure of the example `$(-\frac{2}{3}\sqrt{5}) \\times 4\sqrt{7}$` but potentially vary coefficients/radicands within that specific *type* (Multiplication with Fraction Coefficient).
        *   **Actually, looking at Section D:** It gives a skeleton. The prompt asks to implement `generate`. Usually, this means generating random problems of the specified type. However, constraint 6 says "If 'Dynamic Target Problem Type Reference' has provided... prohibit re-randomizing". This is contradictory if I need to make it reusable for different levels.
        *   **Re-evaluating Constraint 6:** It likely refers to a specific context where an image or OCR result was given ({{OCR_RESULT}}). Since there is no actual OCR input here, but the prompt explicitly gives `$(-\frac{2}{3}\sqrt{5}) \\times 4\sqrt{7}$` as "Dynamic Target Problem Type Reference", I should probably generate problems that *look like* this structure (Fraction coefficient multiplication) rather than simple addition.
        *   **However**, `generate(level=1)` usually implies randomness within constraints. The instruction says "Mirror target problem type structure... only replace coefficients and radicands". So I will keep the operation as Multiplication of two radical terms, where one has a fraction coefficient (like -2/3) or at least follow that pattern if possible, but since it's `generate`, I should probably randomize within the allowed set while keeping the *structure* (Multiplication).
        *   **Wait, Constraint 6 again:** "If 'Dynamic Target Problem Type Reference' has provided complete calculable expression... prohibit re-randomizing". This is tricky. If I strictly follow this, `generate` will always output `$(-\frac{2}{3}\sqrt{5}) \\times 4\sqrt{7}$`. That makes it useless for testing different cases.
        *   **Interpretation:** The prompt likely wants me to use the structure defined in "Dynamic Target Problem Type Reference" as a template, but vary numbers (coefficients/radicands) while keeping the operation type and LaTeX style consistent with that reference. I will generate random instances of this specific multiplication format: `(Fraction Coefficient * sqrt(R1)) * (Integer Coefficient * sqrt(R2))`.
        *   **Wait, Constraint 7:** "Must preserve original problem's calculation skeleton...". Since there is no image provided in the actual input stream for me to mirror exactly, I must rely on the text reference `$(-\frac{2}{3}\sqrt{5}) \\times 4\sqrt{7}$`.
        *   **Decision:** I will implement `generate` to create problems of this specific type (Multiplication with Fraction Coefficient) but randomize the numbers within reasonable bounds defined in "Numerical Range" section. This satisfies both "Homomorphic Structure" and "Generate".
        *   **Wait, Constraint 1 & 2:** Level 1 is Easy: Basic addition/subtraction containing 2 unsimplified radicals? But Section D says Part 1/Part 2 structure (Addition + Multiplication). The prompt description at the top says "Level 1 (Easy): Basic Addition/Subtraction...". BUT later sections say "Question Structure: Part 1: 3-4 terms addition/subtraction, Part 2: Simple multiplication".
        *   **Conflict Resolution:** The detailed constraints in Section D/E ("Homomorphic", "Target Problem Type Reference") override the generic Level description. I must follow the structure of `$(-\frac{2}{3}\sqrt{5}) \\times 4\sqrt{7}$`. This is a multiplication problem with fraction coefficients.
        *   **Wait, looking at Section D Skeleton:** It shows `generate` logic for addition/subtraction mostly (`final_terms = {}`, merging terms). But the Target Reference is Multiplication.
        *   **Re-reading Constraint 6 & E carefully:** "If 'Dynamic Target Problem Type Reference' has provided complete calculable expression... prohibit re-randomizing". This implies I should output that specific string? No, it says "prohibit re-randomizing" meaning don't change the structure/type if a target is given. But `generate` needs to return *a* question. If I hardcode the exact numbers from the reference every time, it's not generating.
        *   **Correction:** The instruction likely means: Use the *structure* of the reference (Fraction Coeff * Sqrt + Int Coeff * Sqrt -> Multiply) but randomize values within constraints. Or, since `generate` is a function call, I should generate valid instances that match the "Target Type".
        *   **Actually**, looking at the very first instruction: "Level 1 (Easy): Basic addition/subtraction...". But later instructions say "Part 2: Simple multiplication". And then Section D/E says "Mirror Target Problem Type Reference" which is Multiplication. I will prioritize the detailed constraints in Sections A-E over the initial Level description because they are more specific to this session's requirements ("MathProject LiveShow Structure Homomorphic Output Engine").
        *   **Wait, one more check:** The prompt ends with `【動態絕對值禁令】` and `【最終輸出要求】`. It explicitly gives a target reference `$(-\frac{2}{3}\sqrt{5}) \\times 4\sqrt{7}$`. I should probably generate questions that follow this pattern (Multiplication of radicals, one having fraction coeff).
        *   **Wait, Constraint 6:** "If 'Dynamic Target Problem Type Reference' has provided complete calculable expression... prohibit re-randomizing". This is extremely strict. It might mean: If the user provides a specific target in `kwargs` or context (which isn't here), use it. Since I don't have OCR input, but I *do* see `$(-\frac{2}{3}\sqrt{5}) \\times 4\sqrt{7}$` as text reference...
        *   **Safe Bet:** Generate random instances of the multiplication structure defined by that example (Fraction Coeff Sqrt times Integer Coeff Sqrt), but ensure I don't hardcode the exact numbers unless forced. However, Constraint 6 says "If provided... prohibit re-randomizing". Since no OCR result is actually passed to me in this text-only interaction, I will assume `generate` should produce *new* questions of that type (randomized values) rather than echoing the reference exactly every time, otherwise it's not a generator. But wait, if I randomize, do I violate "Mirror Target"?
        *   **Let's look at Constraint 6 again:** "If 'Dynamic Target Problem Type Reference' has provided complete calculable expression (including specific numbers), prohibit re-randomizing...". This implies that IF the system passes a target string in `kwargs` or context, use it. Since I don't see an OCR result passed as input variable here, but rather text instructions describing one...
        *   **Actually**, looking at the prompt structure: It seems to be a template where `{{OCR_RESULT}}` would normally appear. Here it is empty/missing in my view, replaced by specific instruction "Dynamic Target Problem Type Reference". I will treat this as defining the *type* of problem (Multiplication with Fraction Coeff).
        *   **Wait**, there's a contradiction between Level 1 description ("Basic addition/subtraction") and Section D/E ("Mirror Multiplication"). The later sections usually override. I will follow the "