Thinking Process:

1.  **Analyze the Request:**
    *   **Role:** K12 Math Algorithm Engineer / MathProject LiveShow Structure Homomorphic Output Engine (Qwen-8B-VL specialized).
    *   **Task:** Implement `def generate(level=1, **kwargs)` to generate radical simplification and arithmetic problems.
    *   **Constraints:**
        *   No thinking process output (`/no_think`).
        *   No markdown fences (```python ... ```).
        *   No explanatory text before or after the code.
        *   Strict adherence to import rules (`import random`, `import math`, `from fractions import Fraction`), no custom imports for ops.
        *   Use injected APIs: `RadicalOps.simplify_term`, `RadicalOps.format_term_unsimplified`, `RadicalOps.format_expression`, `FractionOps.create`.
        *   Logic must be based on integer/fraction operations, not parsing LaTeX strings to get values (except formatting).
        *   Level 1: Single radical simplification.
        *   Level 2: Combining like radicals (addition/subtraction).
        *   Structure Homomorphism: Must mirror the target problem structure if provided (though in this specific prompt, there is a "Dynamic Target Problem Type Reference" section that looks like code snippets to follow or adapt from). However, looking closely at the end of the prompt ("【動態目標題型參考】"), it provides a *specific* example logic for division with fractions.
        *   **Crucial Conflict Resolution:** The prompt contains conflicting instructions between "Level 1/2" definitions and the "Homomorphic Structure" section which seems to demand specific LaTeX formatting (`\times`, `\div`) and Fraction handling even if Level is simple. However, looking at the very last instruction block:
            *   `【動態目標題型參考】` shows a code snippet for division of radicals with fractions.
            *   `【硬性一致性約束（必須遵守）】` says "Strictly mirror target problem type structure...".
            *   BUT, the initial task description defines Level 1 (Simplifying Radicals) and Level 2 (Combining Like Radicals).
            *   The prompt ends with a specific code block example that uses division (`\div`) and Fraction radicands.
            *   **Decision:** I need to follow the core `generate` function definition provided in the "K12 Math Algorithm Engineer" section primarily, but ensure it respects the API usage rules. However, there is a strong instruction at the end: "If 'Dynamic Target Problem Type Reference' provides complete calculable formula... prohibit re-randomizing numbers". This suggests I should perhaps follow the structure of the reference if possible, OR implement Level 1/2 logic as defined in the beginning which seems more standard for this task.
            *   Wait, looking at the very last block: `【動態目標題型參考】` contains a specific code snippet that looks like it was generated by an AI or is part of the prompt's example to be followed closely ("Strictly mirror target problem type structure"). But there isn't actually an image OCR result provided (`{{OCR_RESULT}}`).
            *   The instruction says: "If 'Dynamic Target Problem Type Reference' provides complete calculable formula... prohibit re-randomizing numbers". Since I don't have a specific fixed template to copy (no `OCR_RESULT`), I must generate random problems based on the Level definitions.
            *   However, there is a strong constraint at the end: "Strictly mirror target problem type structure... Do not add operations not in original title." This implies if I choose Level 1/2 as defined earlier, I should stick to that (Add/Sub for Lvl 2). The reference code snippet shows division.
            *   **Resolution:** I will implement the `generate` function based on the initial task definition (Level 1: Simplify single radical, Level 2: Combine like radicals) because there is no specific "Target Problem" image provided to mirror exactly. The instruction about mirroring seems to be a template for when OCR results are present. Since I am generating from scratch (`level=1` or `**kwargs`), I will follow the initial task definition (Level 1/2 logic).
            *   **Wait, re-reading carefully:** The prompt ends with "【動態目標題型參考】" which shows a specific code block for division. But it also says "If 'Dynamic Target Problem Type Reference' provides complete calculable formula... prohibit re-randomizing numbers". Since I am generating new problems (Level 1/2), I should randomize within the constraints of Level 1 or 2.
            *   **BUT**, there is a specific constraint: `【絕對禁止輸出 thinking 或任何非 code 內容】`. This means I must output ONLY Python code, no markdown fences.
            *   There is also a conflict about "Do not add operations...". Level 1 has only simplification (no + -). Level 2 has addition/subtraction. The reference snippet shows division. Since the user prompt asks for `def generate(level=1...)`, I should implement logic that handles level 1 and potentially level 2 if passed, but primarily focus on making it work correctly with the provided APIs (`RadicalOps`).
            *   **Key Constraint:** "Directly output Python code... No markdown". This is critical. The system instruction says `/no_think` at the very top. I must not use ```python ... ```. Just raw text starting with `import`.

2.  **Drafting the Code:**
    *   Imports: `random`, `math`, `from fractions import Fraction`.
    *   Functions: `generate(level=1, **kwargs)`, `check(user_answer, correct_answer)`.
    *   Logic for Level 1 (Simplifying Radicals): Generate a radicand from the "simplifiable" list. Coefficient usually 1 or -1 unless specified otherwise? The prompt says coeff range -5 to 5. For simplification tasks, often just `\sqrt{...}` is expected, but `coeff` can be part of it (e.g., `-2\sqrt{8}`). Let's stick to the definition: "Single term needing simplification".
    *   Logic for Level 2 (Combining Like Radicals): Generate multiple terms with same radicand after simplification. Add/Sub coefficients.
    *   API Usage: `RadicalOps.simplify_term`, `RadicalOps.format_expression`.
    *   Formatting: Use `format_term_unsimplified` for the question text, `format_expression` for the answer key.

3.  **Refining Logic based on "Homomorphic" constraints:**
    The prompt ends with a very specific block about mirroring structure and using `\times`, `\div`. However, Level 1/2 definitions say: Lvl 1 (Simplifying), Lvl 2 (Combining). I will implement these. If `level=3` or similar isn't defined in the initial task but implied by "Homomorphic", I should stick to the explicit definition of Level 1 and 2 provided at the start ("Level 1... Level 2...").
    Actually, looking at the very last instruction block: "If 'Dynamic Target Problem Type Reference' provides complete calculable formula... prohibit re-randomizing numbers". Since there is no OCR result or specific fixed template image data here (it's text), I must generate random ones. The reference code snippet provided in the prompt *is* a target structure example, but it uses division (`\div`). Level 1/2 definitions do not mention multiplication/division explicitly as primary tasks for those levels (Lvl 1: Simplify single term; Lvl 2: Combine like radicals). I will stick to Add/Sub or Single Term logic unless `level` implies otherwise.
    Wait, the prompt says "Level 1... Level 2". It does not define Level 3+. So I should handle level=1 and level=2 specifically as described in the first paragraph of the task description. The later sections about `\times`, `\div` seem to be part of a template for handling OCR results which aren't present here.
    **Correction:** The prompt is extremely cluttered with conflicting instructions (K12 Engineer vs MathProject LiveShow). I need to prioritize the *Task* section at the beginning ("Level 1... Level 2") while adhering to the *API Usage* and *Import Rules*.
    
    However, there's a specific instruction: "【動態絕對值禁令】圖片中沒有絕對值符號。嚴禁在你的程式碼中加入 abs()". This is relevant if I were generating absolute value problems. Since Level 1/2 don't use them, this is fine.
    
    **Critical Constraint:** "Directly output Python code... No markdown fences". The system instruction `/no_think` and the prompt's top line `【絕對禁止輸出 thinking 或任何非 code 內容】` combined with `- 直接輸出 Python code，沒有任何前言、後語`. I must not wrap it in ```python.

    **Wait, one more check:** "嚴禁寫 'Okay, I need to...'".
    
    Okay, let's write the code based on Level 1 and Level 2 logic using `RadicalOps` APIs provided in the prompt description (even though they are injected).
    
    *   Imports.
    *   Define lists for simplifiable radicands (`[8, 12, ...]`) and simple ones (`[2, 3, ...]`).
    *   Function `generate`: