Thinking Process:

1.  **Analyze the Request:**
    *   **Role:** K12 Math Algorithm Engineer (Fraction Arithmetic Expert) & MathProject LiveShow Structure Isomorphic Engine (Qwen-8B-VL Specific).
    *   **Task:** Generate Python code for a math problem generator based on specific constraints, primarily focusing on "Structure Isomorphism" and "Fraction Display".
    *   **Input Data:** The user provided detailed instructions including:
        *   Fraction display rules (Mixed vs. Improper based on prompt markers or defaults).
        *   Step D6 validation logic (O(1) smart inversion & verification, filtering by value size).
        *   Forbidden items (no random operators changing structure, no decimals, etc.).
        *   A specific "Dynamic Target Problem Type Reference" example: `$(-2\frac{1}{6})+1\frac{2}{9}-(-1\frac{1}{3})$`.
        *   **Crucial Constraint:** If the "Dynamic Target Problem Type Reference" provides a complete calculable expression (with specific numbers), I must NOT randomly regenerate numbers or rewrite it into another problem. I must preserve the original calculation skeleton, number of terms, brackets, absolute value positions, sign configuration, and operator set exactly as provided in that reference example if applicable to this generation task context.
        *   **Crucial Constraint:** The user's prompt ends with "If 'Dynamic Target Problem Type Reference' has already provided a complete calculable expression (containing specific numbers), prohibit re-randomizing numbers, prohibit rewriting into other problems." AND "Must preserve the original problem calculation skeleton: number of terms, bracket levels, absolute value positions, sign configuration and operator set must be consistent."
        *   **Output Requirement:** Only output raw Python code. No markdown explanations, no JSON (except inside strings if needed for structure), but specifically "Do not output Markdown". Wait, the instruction says "Only output Python original code... Do not output any extra text... Do not output markdown." However, standard practice in this environment often requires a code block or just raw text. The prompt explicitly says: `【G. 最終輸出要求】 - 只輸出 Python 原始碼。- 不要輸出任何額外文字。- 不要輸出 markdown.`
        *   **Conflict Resolution:** There is a conflict between the general instruction "Do not output Markdown" and the fact that I am an AI model usually expected to use code blocks. However, strict adherence means raw text or just ` ```python ... ``` `. Given the constraint "Only output Python original code", I should probably avoid markdown fences if strictly interpreted, but standard practice for "Python Code" requests is often a fenced block. Let's look closer: "Do not output any extra text... Do not output markdown." This usually means no introductory sentences like "Here is the code:". But to ensure it's recognized as Python by users/tools, I will use raw text or minimal formatting if allowed. However, looking at previous interactions with similar constraints in this persona context (MathProject LiveShow), often a ` ```python ` block is acceptable for clarity unless explicitly forbidden *inside* the markdown itself. The instruction says "Do not output Markdown". This likely means don't wrap it in `markdown` explanation text or use headers like "# Code". But to be safe and compliant with "Only output Python original code", I will provide the raw content without surrounding markdown fences if possible, OR just standard python block syntax which is technically markdown. Let's re-read: "Do not output Markdown." This usually implies no ` ```python `. It wants *raw* text that looks like a script or file content? Or does it mean don't add explanations? Usually, for code generation tasks in this specific persona context (Qwen-8B-VL), the user expects a standard Python block. But "Do not output Markdown" is quite strict. I will interpret this as: Do not write `Here is your code:` or use markdown headers like `## Code`. Just the code itself, potentially inside a triple backtick if that counts as 'Markdown' (it does). To be safest with "No Markdown", I should avoid ```python and just output the text. However, most LLM interfaces render raw text poorly for code highlighting. Let's look at instruction 5: `Do not output JSON`. Instruction G says `Only output Python original code.`
        *   Wait, there is a specific constraint in Section F (Skeleton) that defines how to generate numbers (`IntegerOps.random_nonzero`). But the "Dynamic Target Problem Type Reference" section (G. Final Output Requirements context?) actually overrides this for *this* task if it provides specific numbers? The prompt says: `【動態目標題型參考】$(-2\frac{1}{6})+1\frac{2}{9}-(-1\frac{1}{3})$ 【題型同構硬性約束】...`.
        *   **Critical Decision:** Does the user want me to generate a NEW problem based on this structure, or use THIS specific example as the ONLY output? The instruction says: "If 'Dynamic Target Problem Type Reference' has already provided a complete calculable expression (containing specific numbers), prohibit re-randomizing numbers...". This implies I should NOT randomize. But Section F defines `generate` function logic with loops and randomness (`for _ in range(100)`).
        *   **Interpretation:** The user wants the code structure defined by Section F, but when generating a problem instance (inside that loop), if there is a "Target Problem Type Reference" provided as input to this session context, I must respect it. However, usually, in these prompts, the "Reference" describes *what kind* of problems are allowed or expected for future generations, OR it acts as a hard constraint on the current generation logic (i.e., don't deviate from that specific example's structure).
        *   **Re-reading Section G:** `【G. 最終輸出要求】... 6) 若「動態目標題型參考」已提供完整可計算算式（含具體數字），禁止重新隨機抽數、禁止改寫為其他題目。7) ...` This looks like a rule for the *generation logic* inside the code, OR it's an instruction to me (the AI). Given I am generating Python code that defines `generate`, and this prompt contains specific numbers in "Dynamic Target Problem Type Reference", if I follow Rule 6 strictly within my own generated code, I would need to hardcode those numbers or ensure the random generation respects them. But usually, these prompts want a *generator* script where the logic follows the rules (like mixed fractions), but the example provided is just an illustration of what "Mixed Fraction" looks like in LaTeX (`-2 \frac{1}{6}`).
        *   **Wait, looking at Section F:** It defines `generate` with random numbers. If I follow Rule 6 ("If reference provides complete expression... prohibit re-randomizing"), it implies the output should be based on that specific example? No, usually this instruction means "When you generate a problem for testing/evaluation in your head or if asked to solve *that* specifically". But here I am writing code.
        *   **Most likely interpretation:** The user wants me to write the Python script (Section F) but ensure it adheres to all constraints listed (Fraction display, Mixed vs Improper logic based on flags - though no flag is passed in `generate`, so default mixed=False per Section D1? Wait, Section G says "Preserve original problem calculation skeleton...". The example `$(-2\frac{1}{6})+1\frac{2}{9}-(-1\frac{1}{3})$` has specific numbers.
        *   **Actually**, looking at the instruction `【動態目標題型參考】`, it seems to be part of the prompt context defining what kind of problem I should generate or how I should handle a "Target". However, since this is a code generation task (Output Python Code), and Section F defines the structure with randomization (`for _ in range(100)`... `IntegerOps.random_nonzero`), if I hardcode specific numbers from that reference into the generator loop, it defeats the purpose of a "generator".
        *   **Correction:** The instruction says: "If 'Dynamic Target Problem Type Reference' has already provided a complete calculable expression (containing specific numbers)... prohibit re-randomizing...". This is likely an instruction for me to follow regarding the *content* I generate if this were a direct problem solving task. Since it's asking for Python code, I should write the `generate` function as per Section F logic (which uses random), BUT ensure that any "Target" provided in the prompt context overrides randomness? No, usually these prompts are templates where the user pastes constraints and expects me to output the *code* implementing those constraints. The specific numbers `$(-2\frac{1}{6})+...$` might be an example of what `mixed=True` looks like (as per Section D).
        *   **Wait, one more check:** "If 'Dynamic Target Problem Type Reference' has already provided a complete calculable expression ... prohibit re-randomizing numbers". This is in the list under G. It implies I should NOT randomize if that reference exists. But since this prompt IS providing that reference (the example with -2 1/6 etc), does it mean I must output code that generates *that specific problem*? Or just ensure my generator logic doesn't break structure like mixed fractions?
        *   **Safest Path:** The user wants the Python Code defined in Section F, but adhering to all constraints (Fraction display rules). The "Reference" example