Thinking Process:

1.  **Analyze the Request:**
    *   **Role:** K12 Math Algorithm Engineer / MathProject LiveShow Structure Homomorphic Output Engine (Qwen-8B-VL specialized).
    *   **Task:** Implement `def generate(level=1, **kwargs)` to generate radical simplification and arithmetic problems.
    *   **Constraints:**
        *   NO thinking process output.
        *   NO markdown fences (` ```python `).
        *   NO explanations or comments outside the code logic (though internal docstrings are usually okay if they don't violate "no non-code content", but strict instruction says "Directly output Python code, no preamble/postscript"). The prompt explicitly says "嚴禁寫任何思考過程、解釋、註解" and "直接輸出 Python code，沒有任何前言、後語". I need to be careful about comments inside the function. Usually, docstrings are part of the code structure, but excessive comments might violate "no explanation". However, standard coding practice includes minimal comments for logic flow. The prompt says "嚴禁寫任何思考過程... 直接輸出 Python code". I will keep internal comments minimal and focused on logic steps required by the system injection rules (like `# Step 0: ...`).
        *   Must import `random`, `math`, `from fractions import Fraction`.
        *   MUST NOT use `import RadicalOps` or `import FractionOps` (they are injected). Use them directly.
        *   Level 1: Single radical simplification (`\sqrt{...}`). No arithmetic operations between terms.
        *   Level 2: Combining like radicals (addition/subtraction of multiple terms, e.g., $3\sqrt{12} - \sqrt{27}$). No multiplication/division in the generated problem text for this specific level definition based on the initial task description ("Level 2 ... only generate addition/subtraction..."). However, there is a conflicting section "【動態目標題型參考】" which shows division examples. The prompt structure has two parts:
            *   Part 1 (K12 Math Algorithm Engineer): Defines Level 1 and Level 2 clearly (Simplifying vs Combining Like Radicals).
            *   Part 2 (MathProject LiveShow Structure Homomorphic Output Engine): This seems to be a system prompt override or additional context that emphasizes "Homomorphic Imitation" based on OCR results. However, the user instruction at the very beginning says: "【任務】實作 `def generate(level=1, **kwargs)`... Level 1 (Easy)... Level 2 (Normal)".
            *   The later section "[動態目標題型參考]" shows a division example (`\div`). But the initial task definition for Level 2 explicitly says "不包含乘除法" (does not contain multiplication/division).
            *   There is also a constraint: "【最高優先原則】你不是在「自由出題」，你是在「同構模仿」。必須複製原例題的根式結構...". This suggests I should look at the provided example in `[動態目標題型參考]`? No, that section says "[範例題型] {{OCR_RESULT}}" which is a placeholder.
            *   Crucially, there are conflicting instructions regarding Level 2 (Add/Sub only vs Division examples). The initial task definition ("Level 1... Level 2") seems to be the primary functional requirement for `generate`. The "MathProject LiveShow" section looks like system context or style guidance that might conflict.
            *   However, looking closely at the prompt structure: It starts with `/no_think` and strict constraints. Then it defines Role/Task (Level 1 & 2). Then there is a large block of text about "MathProject LiveShow Structure Homomorphic Output Engine". This looks like a few-shot or system instruction injection that might be trying to override the simple Level 1/2 definition with complex homomorphism rules.
            *   BUT, the user prompt ends with: `【硬性一致性約束（必須遵守）】...`. And specifically asks for Python code ONLY.
            *   The most critical constraint is "Level 1 (Easy): ... only generate single term... Level 2 (Normal): Combining Like Radicals". I should stick to this definition unless the OCR result implies otherwise. Since there is no actual OCR image provided, just text placeholders like `{{OCR_RESULT}}`, I must rely on the explicit task description for Levels 1 and 2 defined in the first section ("【任務】").
            *   Wait, looking at the very end: "若「動態目標題型參考」已提供完整可計算算式...". Since there is no actual image/OCR result provided (it's text), I should follow the Level definitions. However, the prompt includes a specific example code block in `[E. 最終輸出要求]` which shows division logic (`\div`).
            *   Actually, looking at the very beginning: "【任務】實作 `def generate(level=1, **kwargs)`...". Then later there is "[動態目標題型參考]" showing a specific example with `\div`. This suggests I might need to handle multiplication/division if requested or implied by level?
            *   Re-reading the Level 2 definition: "Level 2 (Normal): ... only generate addition/subtraction of like radicals... does not contain multiplication/division".
            *   The later section says "【A. 硬性同構規範】... Multiplication and division block form must be kept...". This contradicts Level 2's initial description if I assume the system prompt overrides the task definition.
            *   However, usually in these prompts, the first explicit instruction ("Level 1/2") is the functional spec for `generate`. The later text looks like "System Instructions" that might be noise or context from a different session merged into this request. But I must follow the most recent and strict constraints.
            *   Let's look at the constraint: "【任務】實作... Level 1 ... Level 2". This is the core task. The later text about "MathProject LiveShow" seems to be part of a larger context that might expect me to handle OCR results, but since I don't have an image, I should default to the defined Levels (Level 1: Simplify single radical; Level 2: Add/Sub like radicals).
            *   Wait, there is a specific instruction in `[E. 最終輸出要求]` that says "Do not output JSON... Do not output markdown". And it shows an example code block with division logic inside `generate`. This suggests I should perhaps implement the more complex version if possible? No, Level 2 definition explicitly forbids multiplication/division ("不包含乘除法").
            *   Okay, let's prioritize the explicit "Level" definitions in the first section. If level=1 -> Simplify single radical. If level=2 -> Add/Sub like radicals (no mult/div). The later text about division seems to be part of a template that might not apply if I strictly follow Level 1/2 specs provided at the start.
            *   However, there is also "【最高優先原則】... Must copy original example's radical structure". Since no OCR result exists (it says `{{OCR_RESULT}}`), I cannot imitate an image. I must generate based on logic.
            *   Let's check the imports: `import random`, `import math`, `from fractions import Fraction`.
            *   Logic for Level 1: Pick a radicand from `simplifiable = [8, 12, ...]`. Simplify it using `RadicalOps.simplify_term(1, r)`. Format as `\sqrt{...}`. Question text: "化簡 $\sqrt{r}$".
            *   Logic for Level 2: Pick multiple radicands (e.g., 3 terms). Coefficients from -5 to 5. Use `RadicalOps.format_term_unsimplified` for question parts. Combine them using a dictionary of coefficients per simplified radical in the answer calculation. Format final expression with `RadicalOps.format_expression`.
            *   The prompt includes specific instructions about handling Fraction coefficients and division logic (`r1 / r2`). But Level 2 says "No multiplication/division". I will stick to Add/Sub for Level 2 as defined in the first section, but ensure robustness. If level=3 or higher isn't specified, default to provided levels.
            *   Wait, looking at `[E. 最終輸出要求]` example code: It uses `r1 = Fraction(random.choice(simplifiable), random.choice(simplifiable))`. This creates a fraction radicand (e.g., $\sqrt{A}/\sqrt{B}$). The prompt says "Level 2 ... Combining Like Radicals".
            *   I need to make sure the code handles `level` parameter. If level=1, do single radical simplification. If level=2, do addition/subtraction of radicals (like terms).
            *   Constraint: "嚴禁寫任何思考過程... 直接輸出 Python code，沒有任何前言、後語". No markdown fences around the whole block? Usually ` ```python ` is considered formatting. The instruction says "禁止 markdown fence" in section B ("Qwen-8B-VL Specialized"). So I should output raw text starting with imports and functions, no triple backticks.
            *   Wait, standard Python code blocks usually have fences for readability. But the constraint says "禁止 markdown fence". This means I must print just the source code characters without ` ```python `.
            *   Also: "嚴禁寫任何思考過程、解釋、註