Thinking Process:

1.  **Analyze the Request:**
    *   **Role:** K12 Math Algorithm Engineer / MathProject LiveShow Structure Homomorphic Output Engine (Qwen-8B-VL specialized).
    *   **Task:** Implement `def generate(level=1, **kwargs)` to generate radical simplification and arithmetic problems.
    *   **Constraints:**
        *   NO thinking process output.
        *   NO markdown fences (` ```python `).
        *   NO explanations or comments that violate the "code only" rule (though internal logic comments are usually okay, I need to be careful about verbosity). The prompt says "Directly output Python code, no preamble/postscript". It also says "Strictly follow import rules", "Core Logic", etc.
        *   **Crucial:** The user provided a very specific set of instructions that seem contradictory or layered (K12 Math vs Qwen-8B-VL Homomorphic). I need to synthesize the requirements into a single, valid Python script.
        *   **Key Constraint from "Homomorphic" section:** It says "If 'Dynamic Target Problem Type Reference' provides complete calculable expression... prohibit re-randomizing numbers". However, looking at the provided example code in the prompt's end (`【動態目標題型參考】`), it shows a specific structure for division of radicals with Fraction radicands.
        *   **Key Constraint from "K12 Math" section:** It defines Level 1 (Simplifying Radicals) and Level 2 (Combining Like Radicals). The prompt asks to implement `generate(level=1, ...)` but the homomorphic instructions suggest mirroring a specific structure if provided.
        *   **Conflict Resolution:** The prompt ends with "【動態目標題型參考】" which shows a division problem (`\div`). However, the initial task description says Level 1 is simplifying radicals (single term), Level 2 is combining like terms (addition/subtraction). The homomorphic section seems to override or refine this for specific cases.
        *   **Wait, looking closer at the prompt structure:** It looks like a few-shot prompting style where I need to output code that fits the "MathProject LiveShow" persona but adheres to the K12 logic defined earlier (Level 1/2). The final section says "If 'Dynamic Target Problem Type Reference' provides complete calculable expression... prohibit re-randomizing". But there is no *image* or specific target image provided in this text-only context, only a code snippet example at the end.
        *   **Actually**, looking at the very last block `【動態目標題型參考】`, it contains Python code that looks like an attempt to solve a division problem with fractions inside radicals (`Fraction(random.choice(simplifiable), random.choice(simplifiable))`). This is mathematically weird for K12 (usually radicands are integers).
        *   **Re-reading the "K12 Math" section:** It explicitly defines `simplifiable` and `simple` lists. Level 1: Single radical simplification. Level 2: Combining like radicals.
        *   **Re-reading the "Homomorphic/Qwen" section:** This seems to be a system instruction override trying to force me into a specific format that might conflict with K12 logic (e.g., using `Fraction` for radicands). The prompt says "Strictly follow import rules", "Core Logic".
        *   **Decision:** I must prioritize the functional requirements of generating valid math problems based on Level 1/2 definitions provided in the first half, while adhering to the API usage (`RadicalOps`, `FractionOps`) and code structure constraints (imports, no markdown). The homomorphic section seems to be a template for *how* to handle specific complex cases if they existed, but since I am generating Level 1/2 problems based on the K12 definition first, I should stick to integer radicands unless forced otherwise. However, the prompt ends with "【動態目標題型參考】" which shows `Fraction` usage for radicands in a division context.
        *   **Wait, one more check:** The instruction says "If 'Dynamic Target Problem Type Reference' provides complete calculable expression... prohibit re-randomizing". But there is no image or specific target text provided to me as input data, only the prompt itself contains an example block at the end. This looks like a system prompt injection where I need to output code that *could* handle such cases but primarily follows the K12 Level 1/2 logic defined earlier (`simplifiable` list).
        *   **Actually**, looking at the very last instruction: "【硬性一致性約束】... 6. 若「動態目標題型參考」已提供完整可計算算式（含具體數字），禁止重新隨機抽數、禁止改寫為其他題目。" (If Dynamic Target Problem Type Reference provides complete calculable expression..., prohibit re-randomizing).
        *   **BUT**, the text provided in `【動態目標題型參考】` is actually a code snippet example, not an image OCR result. It shows random choices again (`random.choice`). So it's likely just showing me how to structure the division case if I were doing that. Since my task definition says Level 1 (Simplifying) and Level 2 (Combining), I should probably stick to those unless `level` implies otherwise.
        *   **Wait, looking at the very first instruction:** "【絕對禁止輸出 thinking 或任何非 code 內容】". This is critical. I must output ONLY Python code. No markdown blocks like ```python ... ```. Just raw text starting with imports or function definitions? Usually, standard practice for these constraints is to avoid markdown fences if explicitly forbidden ("不要輸出 markdown").
        *   **Wait, another constraint:** "直接輸出可執行 Python 程式碼（需包含 `generate`，可包含 `check`）".
        *   **Constraint Check:** The prompt says "嚴禁寫任何思考過程... 直接輸出 Python code，沒有任何前言、後語". It also says "禁止 markdown fence" in the Qwen section. So I should output raw text starting with imports or function definitions without ```python markers? Or does it mean don't wrap the whole thing in a block but use standard formatting? Usually, for LLMs, if asked not to use markdown fences, I just write the code directly.
        *   **However**, looking at the "K12 Math" section: It defines `generate` and `check`. The Qwen section says "Output must be Python code ONLY".
        *   **Let's look at the imports:** Must import `random`, `math`, `from fractions import Fraction`. Cannot use custom classes.
        *   **Logic:** Level 1 -> Single radical simplification (e.g., `\sqrt{12}`). Level 2 -> Combining like radicals (e.g., `3\sqrt{5} - \sqrt{45}`). The prompt asks to implement `generate(level=1, ...)` but the Qwen section talks about mirroring structure. Since I don't have an image input here, I will follow the K12 Level 1/2 logic defined in the first half as it's more robust for text generation without OCR context.
        *   **Wait**, there is a specific instruction: "【動態絕對值禁令】圖片中沒有絕對值符號。嚴禁在你的程式碼中加入 abs()...". This implies I should check if `level` or kwargs imply absolute values? No, just don't add them randomly.
        *   **Crucial:** The prompt ends with a code snippet that uses `Fraction` for radicands in division (`r1 = Fraction(...)`). But the K12 section says "radicand: 2, 3, 5...". I will stick to integer radicands as per Level 1/2 definition unless level implies otherwise. The prompt asks me to implement `generate(level=1)`.
        *   **Wait**, there is a conflict between the K12 section (Level 1: Simplify Radicals) and the Qwen Homomorphic section (which talks about division). Since I am asked to generate Level 1/2, I will focus on that. The homomorphic instructions seem to be generic constraints for *any* problem generation task in this session context ("MathProject LiveShow").
        *   **Wait**, looking at the very last block `【動態目標題型參考】`, it shows a division example using Fractions inside radicals. This is likely an error or specific edge case handling instruction. Given I am generating Level 1 (Simplifying), I should not generate Division problems unless specified by level logic that isn't fully defined in the K12 section but implied here?
        *   **Actually**, looking at `generate(level=1, ...)` definition: "Level 1... Only single term simplification". So Level 1 = Simplify `\sqrt{N}`. Level 2 = Combine like terms (Add/Sub). I will implement this logic strictly as per the K12 section because that's where the specific problem types are defined for `level`. The Qwen/Homomorphic part seems to be a template override, but since there is no image input (`{{OCR_RESULT}}`), I cannot mirror an OCR result. So I must generate based on Level 1/2 definitions provided in text.
        *   **Wait**, the prompt says "【任務】實作 `def generate(level=1, ...)`". It defines Level 1 and Level 2 logic clearly at the start. The Qwen section seems to be a system instruction layer